# Generated by Django 5.0.2 on 2024-02-16 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('gender', models.CharField(max_length=255)),
                ('hair_color', models.CharField(max_length=255)),
                ('skin_color', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
